name: SpawnW0dka
version: 1.0
main: pl.spawnw0dka.SpawnW0dka
api-version: '1.21'

commands:
  sw:
    description: Zarządzanie regionami SpawnW0dka
    usage: /sw <wand|create|delete|list>
    permission: spawnw0dka.admin

permissions:
  spawnw0dka.admin:
    description: Dostęp do komend SpawnW0dka
    default: op
